<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Template\TemplateBuild;

class TemplateBuildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {        
        $builds = [
            // ===== BÂTIMENTS =====
            // ENERGIE
            [
                'uuid' => 'b2000000-0000-0000-0000-000000000001',
                'name' => 'centrale_solaire',
                'label' => 'Centrale Solaire',
                'description' => "Produit l'énergie pour vos bâtiments et flottes. Essentiel pour soutenir la production et les missions spatiales.",
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_FACILITY,
                'icon' => 'solar_plant.png',
                'max_level' => 30,
                'base_build_time' => 120,
                'is_active' => true,
            ],

            // PRODUCTION
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000001',
                'name' => 'mine_fer',
                'label' => 'Mine de Fer',
                'description' => 'Génère du Fer en continu. Ressource de base pour la construction de bâtiments et d’unités.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'iron_mine.png',
                'max_level' => 30,
                'base_build_time' => 360, // 6 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000002',
                'name' => 'extracteur_cristal',
                'label' => 'Mine de Cristal',
                'description' => 'Extrait du Cristal en continu. Ressource clé pour technologies avancées et vaisseaux.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'crystal_extractor.png',
                'max_level' => 30,
                'base_build_time' => 300, // 5 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000003',
                'name' => 'raffinerie_deuterium',
                'label' => 'Mine de Deutérium',
                'description' => 'Raffine du Deutérium en continu. Carburant des flottes et nécessaire à certaines recherches.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'deuterium_refinery.png',
                'max_level' => 30,
                'base_build_time' => 720, // 12 minutes
                'is_active' => true,
            ],

            // STOCKAGE
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000007',
                'name' => 'stockage_fer',
                'label' => 'Stockage de Fer',
                'description' => 'Augmente la capacité de stockage de Fer. Évite la saturation et prépare les envois de transport.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'iron_storage.png',
                'max_level' => 30,
                'base_build_time' => 2400, // 40 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000008',
                'name' => 'stockage_cristal',
                'label' => 'Stockage de Cristal',
                'description' => 'Augmente la capacité de stockage de Cristal. Sécurise les réserves pour constructions et technologies.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'crystal_storage.png',
                'max_level' => 30,
                'base_build_time' => 2700, // 45 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b1000000-0000-0000-0000-000000000009',
                'name' => 'stockage_deuterium',
                'label' => 'Stockage de Deutérium',
                'description' => 'Augmente la capacité de stockage de Deutérium. Garantit l’autonomie des flottes sur la durée.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESOURCE,
                'icon' => 'deuterium_storage.png',
                'max_level' => 30,
                'base_build_time' => 3000, // 50 minutes
                'is_active' => true,
            ],

            [
                'uuid' => 'cc000000-0000-0000-0000-000000000001',
                'name' => 'centre_commandement',
                'label' => 'Centre de Commandement',
                'description' => 'Bâtiment central de gestion. Débloque la plupart des constructions et fonctions de la planète.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_FACILITY,
                'icon' => 'command_center.png',
                'max_level' => 30,
                'base_build_time' => 3600, // 60 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b2000000-0000-0000-0000-000000000002',
                'name' => 'centre_recherche',
                'label' => 'Centre de Recherche',
                'description' => 'Produit des points technologiques. Débloque des améliorations impactant production, vitesse et combat.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'research_center.png',
                'max_level' => 30,
                'base_build_time' => 3000, // 50 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b3000000-0000-0000-0000-000000000001',
                'name' => 'caserne',
                'label' => 'Caserne',
                'description' => 'Permet de recruter des unités terrestres pour la défense et l’attaque au sol.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'barracks.png',
                'max_level' => 30,
                'base_build_time' => 2400, // 40 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b4000000-0000-0000-0000-000000000002',
                'name' => 'chantier_spatial',
                'label' => 'Chantier Spatial',
                'description' => 'Construit des vaisseaux spatiaux. Indispensable pour lancer des missions spatiales.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_SHIPYARD,
                'icon' => 'heavy_shipyard.png',
                'max_level' => 30,
                'base_build_time' => 2400, // 40 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b3000000-0000-0000-0000-000000000003',
                'name' => 'plateforme_defensive',
                'label' => 'Plateforme Défensive',
                'description' => 'Autorise l’installation de défenses anti-flottes et anti-unités. Renforce la sécurité planétaire.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'defense_platform.png',
                'max_level' => 30,
                'base_build_time' => 2700, // 45 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 'b2000000-0000-0000-0000-000000000003',
                'name' => 'terraformeur_planetaire',
                'label' => 'Terraformeur Planétaire',
                'description' => 'Augmente la capacité de construction planétaire, permettant davantage de bâtiments et niveaux avancés.',
                'type' => TemplateBuild::TYPE_BUILDING,
                'category' => TemplateBuild::CATEGORY_FACILITY,
                'icon' => 'terraformer.png',
                'max_level' => 30,
                'base_build_time' => 3600, // 60 minutes
                'is_active' => true,
            ],

            // ===== UNITÉS TERRESTRES =====
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000001',
                'name' => 'fantassin_standard',
                'label' => 'Fantassin Standard',
                'description' => "Unité d'infanterie polyvalente, peu coûteuse. Efficace en nombre.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'standard_infantry.png',
                'max_level' => 0,
                'base_build_time' => 60, // 1 minute
                'life' => 100,
                'attack_power' => 25,
                'defense_power' => 15,
                'shield_power' => 0,
                'speed' => 50,
                'cargo_capacity' => 10,
                'fuel_consumption' => 1,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000002',
                'name' => 'commando_tactique',
                'label' => 'Commando Tactique',
                'description' => "Unité d'élite rapide pour infiltration et percée des défenses.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'tactical_commando.png',
                'max_level' => 0,
                'base_build_time' => 180, // 3 minutes // 1.5 minutes // 1 minute
                'life' => 80,
                'attack_power' => 40,
                'defense_power' => 20,
                'shield_power' => 10,
                'speed' => 80,
                'cargo_capacity' => 5,
                'fuel_consumption' => 2,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000003',
                'name' => 'eclaireur_recon',
                'label' => 'Éclaireur Recon',
                'description' => "Reconnaissance terrestre à grande vitesse; révèle infos, faible en combat.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'recon_scout.png',
                'max_level' => 0,
                'base_build_time' => 90, // 1.5 minutes
                'life' => 60,
                'attack_power' => 15,
                'defense_power' => 10,
                'shield_power' => 0,
                'speed' => 120,
                'cargo_capacity' => 0,
                'fuel_consumption' => 1,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000004',
                'name' => 'ingenieur_terrain',
                'label' => 'Ingénieur de Terrain',
                'description' => "Répare structures et véhicules; peut poser des structures temporaires.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_FACILITY,
                'icon' => 'field_engineer.png',
                'max_level' => 0,
                'base_build_time' => 75, // 1.25 minutes
                'life' => 120,
                'attack_power' => 10,
                'defense_power' => 25,
                'shield_power' => 0,
                'speed' => 30,
                'cargo_capacity' => 20,
                'fuel_consumption' => 1,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000005',
                'name' => 'drone_combat',
                'label' => 'Drone de Combat',
                'description' => "Robot de soutien produit en masse; saturer et harceler les ennemis.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'combat_drone.png',
                'max_level' => 0,
                'base_build_time' => 45, // 45 secondes
                'life' => 50,
                'attack_power' => 20,
                'defense_power' => 8,
                'shield_power' => 0,
                'speed' => 60,
                'cargo_capacity' => 0,
                'fuel_consumption' => 1,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000006',
                'name' => 'unite_lourdement_blindee',
                'label' => 'Unité Lourdement Blindée',
                'description' => "Exo‑armure très résistante (rôle de tank); lente mais puissante.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'heavy_armor.png',
                'max_level' => 0,
                'base_build_time' => 120, // 2 minutes
                'life' => 200,
                'attack_power' => 60,
                'defense_power' => 80,
                'shield_power' => 20,
                'speed' => 20,
                'cargo_capacity' => 0,
                'fuel_consumption' => 3,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000007',
                'name' => 'sniper_ionique',
                'label' => 'Sniper Ionique',
                'description' => "Tireur de précision longue portée; neutralise des cibles prioritaires.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'ionic_sniper.png',
                'max_level' => 0,
                'base_build_time' => 60,
                'life' => 275,
                'attack_power' => 120,
                'defense_power' => 40,
                'shield_power' => 10,
                'speed' => 25,
                'cargo_capacity' => 0,
                'fuel_consumption' => 3,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000008',
                'name' => 'technicien_brouillage',
                'label' => 'Technicien de Brouillage',
                'description' => "Perturbe et désactive temporairement les systèmes ennemis (brouillage).",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'jamming_tech.png',
                'max_level' => 0,
                'base_build_time' => 100,
                'life' => 60,
                'attack_power' => 15,
                'defense_power' => 25,
                'shield_power' => 10,
                'speed' => 45,
                'cargo_capacity' => 0,
                'fuel_consumption' => 2,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000009',
                'name' => 'pyrosoldat',
                'label' => 'Pyrosoldat',
                'description' => "Attaques de zone thermiques; très efficace contre groupes serrés.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'pyro_soldier.png',
                'max_level' => 0,
                'base_build_time' => 80,
                'life' => 80,
                'attack_power' => 45,
                'defense_power' => 30,
                'shield_power' => 5,
                'speed' => 35,
                'cargo_capacity' => 0,
                'fuel_consumption' => 2,
                'is_active' => true,
            ],
            [
                'uuid' => 'u1000000-0000-0000-0000-000000000010',
                'name' => 'operateur_artillerie',
                'label' => 'Opérateur d\'Artillerie',
                'description' => "Artillerie lourde terrestre. Déploie canons à dégâts élevés; nécessite protection en mobilité.",
                'type' => TemplateBuild::TYPE_UNIT,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'artillery_operator.png',
                'max_level' => 0,
                'base_build_time' => 150,
                'life' => 70,
                'attack_power' => 80,
                'defense_power' => 15,
                'shield_power' => 0,
                'speed' => 25,
                'cargo_capacity' => 0,
                'fuel_consumption' => 2,
                'is_active' => true,
            ],

            // ===== VAISSEAUX SPATIAUX =====
            [
                'uuid' => 's1000000-0000-0000-0000-000000000001',
                'name' => 'drone_stratos',
                'label' => 'Drone Stratos',
                'description' => 'Éclaireur rapide dédié à l’exploration. Permet les missions d’exploration et la reconnaissance initiale des positions.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_SHIPYARD,
                'icon' => 'stratos_drone.png',
                'max_level' => 0,
                'base_build_time' => 60,
                'life' => 150,
                'attack_power' => 30,
                'defense_power' => 20,
                'shield_power' => 10,
                'speed' => 200,
                'cargo_capacity' => 250,
                'fuel_consumption' => 5,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000002',
                'name' => 'intercepteur_solaire',
                'label' => 'Intercepteur Solaire',
                'description' => 'Chasseur d’interception pour l’attaque spatiale. Excellente escorte et capacité d’engagement rapide contre les flottes ennemies.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'solar_interceptor.png',
                'max_level' => 0,
                'base_build_time' => 90,
                'life' => 200,
                'attack_power' => 80,
                'defense_power' => 40,
                'shield_power' => 30,
                'speed' => 300,
                'cargo_capacity' => 300,
                'fuel_consumption' => 8,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000003',
                'name' => 'bombardier_vector',
                'label' => 'Bombardier Vector',
                'description' => 'Bombardier orbital pour l’attaque spatiale. Optimisé pour frapper les infrastructures et défenses ennemies depuis l’espace.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'vector_bomber.png',
                'max_level' => 0,
                'base_build_time' => 600,
                'life' => 400,
                'attack_power' => 150,
                'defense_power' => 60,
                'shield_power' => 80,
                'speed' => 180,
                'cargo_capacity' => 350,
                'fuel_consumption' => 15,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000004',
                'name' => 'transporteur_delta',
                'label' => 'Transporteur Delta',
                'description' => 'Vaisseau de transport et d’extraction. Indispensable pour les missions de transport et d’extraction de ressources.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_SHIPYARD,
                'icon' => 'delta_transport.png',
                'max_level' => 0,
                'base_build_time' => 480,
                'life' => 600,
                'attack_power' => 40,
                'defense_power' => 100,
                'shield_power' => 120,
                'speed' => 120,
                'cargo_capacity' => 2000,
                'fuel_consumption' => 12,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000005',
                'name' => 'fregate_defensive',
                'label' => 'Frégate Défensive',
                'description' => 'Frégate d’escorte et de protection. Renforce les flottes en transport/extraction et en attaque spatiale grâce à ses boucliers.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'defensive_frigate.png',
                'max_level' => 0,
                'base_build_time' => 720,
                'life' => 800,
                'attack_power' => 100,
                'defense_power' => 150,
                'shield_power' => 200,
                'speed' => 100,
                'cargo_capacity' => 750,
                'fuel_consumption' => 18,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000006',
                'name' => 'croiseur_orion',
                'label' => 'Croiseur Orion',
                'description' => 'Croiseur polyvalent pour l’attaque spatiale. Bon équilibre entre puissance de feu et résistance pour les engagements prolongés.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'orion_cruiser.png',
                'max_level' => 0,
                'base_build_time' => 7200, // 2 heures
                'life' => 1200,
                'attack_power' => 200,
                'defense_power' => 120,
                'shield_power' => 150,
                'speed' => 140,
                'cargo_capacity' => 500,
                'fuel_consumption' => 25,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000007',
                'name' => 'vaisseau_commandement',
                'label' => 'Vaisseau de Commandement',
                'description' => 'Navire de colonisation. Nécessaire pour lancer une mission de colonisation et établir une nouvelle planète.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'command_ship.png',
                'max_level' => 0,
                'base_build_time' => 5400, // 1h30
                'life' => 1000,
                'attack_power' => 120,
                'defense_power' => 180,
                'shield_power' => 250,
                'speed' => 90,
                'cargo_capacity' => 500,
                'fuel_consumption' => 30,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000008',
                'name' => 'plateforme_siege',
                'label' => 'Plateforme de Siège',
                'description' => 'Artillerie orbitale pour l’attaque spatiale. Brise les fortifications ennemies mais reste très lente.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'siege_platform.png',
                'max_level' => 0,
                'base_build_time' => 1800, // 30 minutes
                'life' => 1500,
                'attack_power' => 400,
                'defense_power' => 200,
                'shield_power' => 100,
                'speed' => 50,
                'cargo_capacity' => 500,
                'fuel_consumption' => 40,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000009',
                'name' => 'scout_quantique',
                'label' => 'Scout Quantique',
                'description' => 'Vaisseau d’espionnage furtif. Requis pour les missions d’espionnage et admissible pour l’exploration.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_SHIPYARD,
                'icon' => 'quantum_scout.png',
                'max_level' => 0,
                'base_build_time' => 1800, // 30 minutes
                'life' => 300,
                'attack_power' => 50,
                'defense_power' => 40,
                'shield_power' => 60,
                'speed' => 400,
                'cargo_capacity' => 500,
                'fuel_consumption' => 10,
                'is_active' => true,
            ],
            [
                'uuid' => 's1000000-0000-0000-0000-000000000010',
                'name' => 'dreadnought_nova',
                'label' => 'Dreadnought Nova',
                'description' => 'Vaisseau capital pour l’attaque spatiale. Puissance de feu dominante mais très lent et coûteux en énergie.',
                'type' => TemplateBuild::TYPE_SHIP,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'nova_dreadnought.png',
                'max_level' => 0,
                'base_build_time' => 3600, // 1 heure
                'life' => 3000,
                'attack_power' => 800,
                'defense_power' => 400,
                'shield_power' => 500,
                'speed' => 30,
                'cargo_capacity' => 250,
                'fuel_consumption' => 80,
                'is_active' => true,
            ],

            // ===== DÉFENSES =====
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000001',
                'name' => 'tourelle_cinetique',
                'label' => 'Tourelle Cinétique',
                'description' => 'Tourelle anti-unités légères. Canon à projectiles pour stopper infanterie et drones.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'kinetic_turret.png',
                'max_level' => 0,
                'base_build_time' => 90,
                'life' => 300,
                'attack_power' => 80,
                'defense_power' => 100,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000002',
                'name' => 'canon_laser',
                'label' => 'Canon Laser',
                'description' => 'Défense à faisceau continu. Très efficace contre infanterie et appareils légers.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'laser_cannon.png',
                'max_level' => 0,
                'base_build_time' => 120,
                'life' => 250,
                'attack_power' => 60,
                'defense_power' => 80,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000003',
                'name' => 'lance_missiles',
                'label' => 'Lance-missiles',
                'description' => 'Plateforme de missiles à dégâts de zone et longue portée. Idéale contre formations groupées.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'missile_launcher.png',
                'max_level' => 0,
                'base_build_time' => 360, // 6 minutes
                'life' => 400,
                'attack_power' => 120,
                'defense_power' => 120,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000004',
                'name' => 'batterie_plasma',
                'label' => 'Batterie Plasma',
                'description' => 'Batterie antinavire à plasma. Dégâts élevés contre vaisseaux, consommation énergétique importante.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'plasma_battery.png',
                'max_level' => 0,
                'base_build_time' => 240,
                'life' => 600,
                'attack_power' => 200,
                'defense_power' => 150,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000005',
                'name' => 'champ_brouillage',
                'label' => 'Champ de Brouillage',
                'description' => 'Module de guerre électronique. Réduit précision et verrouillage des attaques ennemies.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'jamming_field.png',
                'max_level' => 0,
                'base_build_time' => 360, // 6 minutes
                'life' => 200,
                'attack_power' => 0,
                'defense_power' => 300,
                'shield_power' => 100,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000006',
                'name' => 'generateur_bouclier',
                'label' => 'Générateur de Bouclier',
                'description' => 'Bouclier de zone. Absorbe une partie des dégâts et protège les infrastructures clés.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'shield_generator.png',
                'max_level' => 0,
                'base_build_time' => 300,
                'life' => 500,
                'attack_power' => 0,
                'defense_power' => 200,
                'shield_power' => 400,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000007',
                'name' => 'tour_surveillance',
                'label' => 'Tour de Surveillance',
                'description' => 'Tour de détection avancée. Révèle unités camouflées et améliore la visibilité tactique.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_FACILITY,
                'icon' => 'surveillance_tower.png',
                'max_level' => 0,
                'base_build_time' => 120,
                'life' => 150,
                'attack_power' => 0,
                'defense_power' => 50,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000008',
                'name' => 'canon_orbital',
                'label' => 'Canon Orbital',
                'description' => 'Plateforme d’artillerie orbitale. Frappe les cibles lourdes depuis l’orbite avec grande puissance.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'orbital_cannon.png',
                'max_level' => 0,
                'base_build_time' => 600,
                'life' => 1000,
                'attack_power' => 500,
                'defense_power' => 300,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000009',
                'name' => 'mines_solaires',
                'label' => 'Mines Solaires',
                'description' => 'Pièges explosifs cachés. S’activent au passage ennemi et désorganisent les assauts.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'solar_mines.png',
                'max_level' => 0,
                'base_build_time' => 60,
                'life' => 50,
                'attack_power' => 300,
                'defense_power' => 10,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],
            [
                'uuid' => 'd1000000-0000-0000-0000-000000000010',
                'name' => 'tourelle_emp',
                'label' => 'Tourelle EMP',
                'description' => 'Tourelle à impulsion EMP. Désactive temporairement boucliers et systèmes adverses pour ouvrir des fenêtres d’attaque.',
                'type' => TemplateBuild::TYPE_DEFENSE,
                'category' => TemplateBuild::CATEGORY_MILITARY,
                'icon' => 'emp_turret.png',
                'max_level' => 0,
                'base_build_time' => 200,
                'life' => 350,
                'attack_power' => 100,
                'defense_power' => 120,
                'shield_power' => 0,
                'speed' => 0,
                'cargo_capacity' => 0,
                'fuel_consumption' => 0,
                'is_active' => true,
            ],

            // ===== TECHNOLOGIES =====
            [
                'uuid' => 't1000000-0000-0000-0000-000000000001',
                'name' => 'espionnage_tactique',
                'label' => 'Espionnage Tactique',
                'description' => 'Permet d\'obtenir des infos avancées sur les bases ennemies.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'tactical_espionage.png',
                'max_level' => 10,
                'base_build_time' => 600,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000002',
                'name' => 'blindage_renforce',
                'label' => 'Blindage Renforcé',
                'description' => 'Augmente la résistance des unités et vaisseaux.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'reinforced_armor.png',
                'max_level' => 15,
                'base_build_time' => 800,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000003',
                'name' => 'vitesse_deploiement',
                'label' => 'Vitesse de Déploiement',
                'description' => 'Réduit le temps de production et de construction.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'deployment_speed.png',
                'max_level' => 12,
                'base_build_time' => 700,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000004',
                'name' => 'stockage_avance',
                'label' => 'Stockage Avancé',
                'description' => 'Augmente les capacités de stockage des ressources.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'advanced_storage.png',
                'max_level' => 10,
                'base_build_time' => 500,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000005',
                'name' => 'efficacite_energetique',
                'label' => 'Efficacité Énergétique',
                'description' => 'Réduit la consommation d\'énergie.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'energy_efficiency.png',
                'max_level' => 15,
                'base_build_time' => 600,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000006',
                'name' => 'armement_ameliore',
                'label' => 'Armement Amélioré',
                'description' => 'Augmente les dégâts de toutes les unités.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'improved_weapons.png',
                'max_level' => 20,
                'base_build_time' => 2400, // 40 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000007',
                'name' => 'portee_optimisee',
                'label' => 'Portée Optimisée',
                'description' => 'Augmente la portée des snipers et défenses.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'optimized_range.png',
                'max_level' => 12,
                'base_build_time' => 1800, // 30 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000008',
                'name' => 'camouflage_numerique',
                'label' => 'Camouflage Numérique',
                'description' => 'Rend certaines unités invisibles à la détection standard.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'digital_camouflage.png',
                'max_level' => 8,
                'base_build_time' => 2700, // 45 minutes
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000009',
                'name' => 'accelerateur_production',
                'label' => 'Accélérateur de Production',
                'description' => 'Boost temporaire de production.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'production_accelerator.png',
                'max_level' => 10,
                'base_build_time' => 650,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000010',
                'name' => 'commandement_strategique',
                'label' => 'Commandement Stratégique',
                'description' => 'Améliore l’efficacité des missions: augmente le taux de collecte et d’exploration par minute selon le niveau.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'strategic_command.png',
                'max_level' => 5,
                'base_build_time' => 1200,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000011',
                'name' => 'armure_reactive',
                'label' => 'Armure Réactive',
                'description' => 'Réduit les dégâts subis par tir (utile contre les attaques de masse).',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'reactive_armor.png',
                'max_level' => 12,
                'base_build_time' => 850,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000012',
                'name' => 'hyperpropulsion',
                'label' => 'Hyperpropulsion',
                'description' => 'Accélère la vitesse des vaisseaux.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'hyperpropulsion.png',
                'max_level' => 15,
                'base_build_time' => 1100,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000013',
                'name' => 'logistique_avancee',
                'label' => 'Logistique Avancée',
                'description' => 'Réduit les coûts de production.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'advanced_logistics.png',
                'max_level' => 10,
                'base_build_time' => 700,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000014',
                'name' => 'science_appliquee',
                'label' => 'Science Appliquée',
                'description' => 'Accélère les recherches.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'applied_science.png',
                'max_level' => 12,
                'base_build_time' => 600,
                'is_active' => true,
            ],
            [
                'uuid' => 't1000000-0000-0000-0000-000000000015',
                'name' => 'champ_inversion',
                'label' => 'Champ d\'Inversion',
                'description' => 'Débloque des dispositifs défensifs de zone.',
                'type' => TemplateBuild::TYPE_RESEARCH,
                'category' => TemplateBuild::CATEGORY_RESEARCH,
                'icon' => 'inversion_field.png',
                'max_level' => 8,
                'base_build_time' => 1300,
                'is_active' => true,
            ],
        ];

        foreach ($builds as $build) {
            TemplateBuild::create($build);
        }
    }
}
